## **데이터 탐색**

**지난 시간에..**

5T 전에는 List 와 Dictionary, for 과 while 문의 사용법을 배웠다.

4T 전에는 Pandas의 Series, DataFrame 을 배웠다.

3T 전에는 Numpy와 Matplotlib.pyplot의 사용법을 배웠다.

2T 전에는 Folium Library의 사용법을 배웠다.

지난 시간에는 대단원 평가를 진행했다.

### **학습 목표**

* Python을 이용하여 median, average, mode를 구한다.
* 알맞은 데이터의 통계를 구한다.

In [1]:
#172.16.200.2(n)

In [3]:
data=[1,2,3,4,5]
avg=sum(data)/len(data)
print(avg)

3.0

In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
avg=np.mean(a)
print("평균값: ",avg)

평균값:  3.0

In [ ]:
import random as rd

li=[]

for i in range(5):
  li.append(rd.randint(1,10))
print("li: {}".format(li))

arr=np.array(li)
print("arr: {}".format(arr))

avg=np.mean(li)
print("avg: ",avg)

In [33]:
import pandas as pd
df=pd.read_csv('/data_01.csv',encoding='cp949')
print(df)
print()
print("average: {:.2f}".format(df['평균기온(°C)'].mean()))
print("median: {}".format(df['평균기온(°C)'].quantile(0.5)))
print("mode :", df['평균기온(°C)'].mode()[0])

print(pd.value_counts(df['평균기온(°C)']))
# pd.Series(obj).value_counts()

     지점          일시  평균기온(°C)
0   143  2019-03-01       8.4
1   143  2019-03-02       8.0
2   143  2019-03-03      10.0
3   143  2019-03-04      10.9
4   143  2019-03-05      10.1
5   143  2019-03-06      11.2
6   143  2019-03-07       8.7
7   143  2019-03-08       8.5
8   143  2019-03-09      10.9
9   143  2019-03-10       8.5
10  143  2019-03-11       8.2
11  143  2019-03-12       8.4
12  143  2019-03-13       5.3
13  143  2019-03-14       6.8
14  143  2019-03-15       6.8
15  143  2019-03-16       7.6
16  143  2019-03-17       8.5
17  143  2019-03-18       9.0
18  143  2019-03-19      13.5
19  143  2019-03-20      12.6
20  143  2019-03-21      13.5
21  143  2019-03-22       7.2
22  143  2019-03-23       6.0
23  143  2019-03-24       6.6
24  143  2019-03-25       9.3
25  143  2019-03-26      11.7
26  143  2019-03-27      15.0
27  143  2019-03-28      12.1
28  143  2019-03-29      12.5
29  143  2019-03-30       9.2
30  143  2019-03-31       6.7

average: 9.41
median: 8.7
mode : 8.5
평균기온(°C)
8.5     3
8.4     2
10.9    2
13.5    2
6.8     2
10.1    1
11.2    1
10.0    1
8.0     1
8.2     1
8.7     1
7.6     1
5.3     1
9.0     1
12.6    1
7.2     1
6.0     1
6.6     1
9.3     1
11.7    1
15.0    1
12.1    1
12.5    1
9.2     1
6.7     1
Name: count, dtype: int64

<ipython-input-33-6e46ee18bf5d>:9: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  print(pd.value_counts(df['평균기온(°C)']))

In [27]:
df2=pd.read_csv('/toilet_2019.csv',encoding='cp949')
print(df2)
print("평균 남성용 소변기 수: {:.2f}".format(df2['남성용-소변기수'].mean()))

               화장실명  남성용-대변기수  남성용-소변기수  남성용-장애인용대변기수  남성용-장애인용소변기수  \
0            덕양구청6층         4         5             0             1
1            덕양구청5층         3         3             1             1
2            덕양구청3층         4         5             0             1
3       덕양구청2층(대강당)         4         4             0             1
4       덕양구청2층(주계단)         4         5             0             1
..              ...       ...       ...           ...           ...
464  덕양종합사회복지관 화장실8         5         8             1             0
465  덕양종합사회복지관 화장실2         5         8             1             0
466  덕양종합사회복지관 화장실5         5         8             1             0
467  덕양종합사회복지관 화장실7         5         8             1             0
468           덕양주유소         1         2             0             0

     남성용-어린이용대변기수  남성용-어린이용소변기수  여성용-대변기수  여성용-장애인용대변기수  여성용-어린이용대변기수
0               0             0         3             0             0
1               0             0         2             1             0
2               0             0         3             0             0
3               0             0         4             0             0
4               0             0         3             0             0
..            ...           ...       ...           ...           ...
464             1             1         8             1             1
465             1             1         8             1             1
466             1             1         8             1             1
467             1             1         8             1             1
468             0             0         2             0             0

[469 rows x 10 columns]
평균 남성용 소변기 수: 6.93